name=GRBL-AGRI3D
version=1.1.0
author=Agri3D Team
maintainer=Agri3D
sentence=Custom FarmBot GRBL Firmware.
paragraph=Stripped of CNC logic and natively mapped to custom relays for Agri3D robotics.
category=Device Control
url=https://mcu.agri3d.local
architectures=avr,megaavr
includes=grbl-agri3d.h
